spring.application.name=collab-workspace

# ?? MySQL ??
# Make sure you have a MySQL database created: CREATE DATABASE collabdb;
spring.datasource.url=jdbc:mysql://localhost:3306/collabdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false